// Generated file

// clang-format off
const char *g_transvoxel_minimal_shader =
"shader_type spatial;\n"
"\n"
"// Default material for VoxelMesherTransvoxel (returned by get_default_lod_material() when no\n"
"// material_override is set on the terrain node). Renders the MIXEL4 per-voxel material blend\n"
"// (CHANNEL_INDICES/CHANNEL_WEIGHTS) via a fixed palette. Not a uniform array: this shader\n"
"// compiler doesn't accept default values on array uniforms (tried both brace-init and the\n"
"// vec4[16](...) constructor form, both failed to parse), so the palette is a plain function\n"
"// instead -- not Inspector-editable, but this is only ever the no-material-assigned fallback.\n"
"// Indices must match EdenPlanetGeneratorV1's MAT_* enum: 0=grass 1=rock 2=snow 3=sand 4=dirt\n"
"// 5=moss 6=ocean_floor.\n"
"vec4 get_material_color(int i) {\n"
"	if (i == 0) {\n"
"		return vec4(0.30, 0.55, 0.20, 1.0); // grass\n"
"	} else if (i == 1) {\n"
"		return vec4(0.45, 0.42, 0.40, 1.0); // rock\n"
"	} else if (i == 2) {\n"
"		return vec4(0.95, 0.97, 1.00, 1.0); // snow\n"
"	} else if (i == 3) {\n"
"		return vec4(0.85, 0.75, 0.45, 1.0); // sand\n"
"	} else if (i == 4) {\n"
"		return vec4(0.35, 0.25, 0.15, 1.0); // dirt\n"
"	} else if (i == 5) {\n"
"		return vec4(0.25, 0.40, 0.22, 1.0); // moss\n"
"	} else if (i == 6) {\n"
"		return vec4(0.30, 0.30, 0.35, 1.0); // ocean floor\n"
"	}\n"
"	return vec4(1.0, 0.0, 1.0, 1.0); // unknown index -- obvious magenta, not a silent guess\n"
"}\n"
"uniform float u_roughness = 0.9;\n"
"\n"
"// From Voxel Tools API\n"
"uniform int u_transition_mask;\n"
"\n"
"float get_transvoxel_secondary_factor(int idata) {\n"
"	int transition_mask = u_transition_mask & 0xff;\n"
"\n"
"	int cell_border_mask = idata & 63; // Which sides the cell is touching\n"
"	int vertex_border_mask = (idata >> 8) & 63; // Which sides the vertex is touching\n"
"	// If the vertex is near a side where there is a low-resolution neighbor,\n"
"	// move it to secondary position\n"
"	int m = transition_mask & cell_border_mask;\n"
"	float t = float(m != 0);\n"
"	// If the vertex lies on one or more sides, and at least one side has no low-resolution neighbor,\n"
"	// don't move the vertex.\n"
"	t *= float((vertex_border_mask & ~transition_mask) == 0);\n"
"\n"
"	// Debugging\n"
"	//t *= 0.5 + 0.5 * sin(TIME * 4.0);\n"
"	//t *= 2.0;\n"
"\n"
"	return t;\n"
"}\n"
"\n"
"vec3 get_transvoxel_position(vec3 vertex_pos, vec4 fdata) {\n"
"	int idata = floatBitsToInt(fdata.a);\n"
"\n"
"	// Move vertices to smooth transitions\n"
"	float secondary_factor = get_transvoxel_secondary_factor(idata);\n"
"	vec3 secondary_position = fdata.xyz;\n"
"	vec3 pos = mix(vertex_pos, secondary_position, secondary_factor);\n"
"\n"
"	// If the mesh combines transitions and the vertex belongs to a transition,\n"
"	// when that transition isn't active we change the position of the vertices so\n"
"	// all triangles will be degenerate and won't be visible.\n"
"	// This is an alternative to rendering them separately,\n"
"	// which has less draw calls and less mesh resources to create in Godot.\n"
"	// Ideally I would tweak the index buffer like LOD does but Godot does not\n"
"	// expose anything to use it that way.\n"
"	int itransition = (idata >> 16) & 0xff; // Is the vertex on a transition mesh?\n"
"	float transition_cull = float(itransition == 0 || (itransition & u_transition_mask) != 0);\n"
"	pos *= transition_cull;\n"
"\n"
"	return pos;\n"
"}\n"
"\n"
"// CUSTOM0/CUSTOM1 are only valid inside vertex() -- capture what fragment() needs into varyings.\n"
"// Not marked flat: matches planet_biome_debug.gdshader's approach of decoding this per-fragment\n"
"// after ordinary interpolation, rather than risking another compiler quirk with that qualifier.\n"
"varying vec2 v_custom1;\n"
"\n"
"void vertex() {\n"
"	VERTEX = get_transvoxel_position(VERTEX, CUSTOM0);\n"
"	v_custom1 = CUSTOM1.xy;\n"
"}\n"
"\n"
"// v_custom1 = MIXEL4 material data: x = packed 4x8 material indices, y = packed 4x8 weights\n"
"// (see transvoxel_materials_common.h add_4i8_4w8_texture_data / transvoxel_materials_mixel4.h).\n"
"void fragment() {\n"
"	uint pi = floatBitsToUint(v_custom1.x);\n"
"	uint pw = floatBitsToUint(v_custom1.y);\n"
"\n"
"	vec4 idx = vec4(float(pi & 0xffu), float((pi >> 8u) & 0xffu), float((pi >> 16u) & 0xffu), float((pi >> 24u) & 0xffu));\n"
"	vec4 w = vec4(float(pw & 0xffu), float((pw >> 8u) & 0xffu), float((pw >> 16u) & 0xffu), float((pw >> 24u) & 0xffu));\n"
"	float wsum = max(w.x + w.y + w.z + w.w, 0.0001);\n"
"\n"
"	vec3 col = get_material_color(int(idx.x)).rgb * w.x;\n"
"	col += get_material_color(int(idx.y)).rgb * w.y;\n"
"	col += get_material_color(int(idx.z)).rgb * w.z;\n"
"	col += get_material_color(int(idx.w)).rgb * w.w;\n"
"	col /= wsum;\n"
"\n"
"	ALBEDO = col;\n"
"	ROUGHNESS = u_roughness;\n"
"}\n";
// clang-format on
