//
// modules\voxel\util\noise\voxel_domain_warp_ispc_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void VoxelDomainWarp2D_FillBuffer(const float OriginX, const float OriginY, const int32_t SizeX, const int32_t SizeY, const float Spacing, const float InAmplitude, const float FeatureScale, const float Lacunarity, const float Gain, const float WeightedStrength, const int32_t NumOctaves, const int32_t InSeed, float * ReturnValuesX, float * ReturnValuesY, const int32_t TotalCount);
    extern void VoxelDomainWarp3D_Batch(const float * PosX, const float * PosY, const float * PosZ, const float InAmplitude, const float FeatureScale, const float Lacunarity, const float Gain, const float WeightedStrength, const int32_t NumOctaves, const int32_t InSeed, float * ReturnValuesX, float * ReturnValuesY, float * ReturnValuesZ, const int32_t Num);
    extern void VoxelDomainWarp3D_FillBuffer(const float OriginX, const float OriginY, const float OriginZ, const int32_t SizeX, const int32_t SizeY, const int32_t SizeZ, const float Spacing, const float InAmplitude, const float FeatureScale, const float Lacunarity, const float Gain, const float WeightedStrength, const int32_t NumOctaves, const int32_t InSeed, float * ReturnValuesX, float * ReturnValuesY, float * ReturnValuesZ, const int32_t TotalCount);
    extern void VoxelNoise_Cellular2D_Batch(const float * PosX, const float * PosY, const int32_t Seed, const float Jitter, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_Cellular3D_Batch(const float * PosX, const float * PosY, const float * PosZ, const int32_t Seed, const float Jitter, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_Perlin2D_Batch(const float * PosX, const float * PosY, const int32_t Seed, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_Perlin3D_Batch(const float * PosX, const float * PosY, const float * PosZ, const int32_t Seed, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_Simplex2D_Batch(const float * PosX, const float * PosY, const int32_t Seed, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_Simplex3D_Batch(const float * PosX, const float * PosY, const float * PosZ, const int32_t Seed, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_TrueDistanceCellular2D_Batch(const float * PosX, const float * PosY, const int32_t Seed, const float Jitter, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_TrueDistanceCellular3D_Batch(const float * PosX, const float * PosY, const float * PosZ, const int32_t Seed, const float Jitter, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_Value2D_Batch(const float * PosX, const float * PosY, const int32_t Seed, float * ReturnValues, const int32_t Num);
    extern void VoxelNoise_Value3D_Batch(const float * PosX, const float * PosY, const float * PosZ, const int32_t Seed, float * ReturnValues, const int32_t Num);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__



#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
