//
// modules\voxel\util\noise\voxel_procedural_noise_ispc_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__

#ifndef __ISPC_STRUCT_FCErosionParams__
#define __ISPC_STRUCT_FCErosionParams__
struct FCErosionParams {
    int32_t Seed;
    float PlanetRadius;
    float TileSize;
    float TriplanarSharpness;
    float HeightFrequency;
    float HeightAmp;
    int32_t HeightOctaves;
    float HeightLacunarity;
    float HeightGain;
    float Scale;
    float Strength;
    float GullyWeight;
    float Detail;
    float RoundingRidge;
    float RoundingCrease;
    float RoundingInputMult;
    float RoundingOctaveMult;
    float OnsetInitial;
    float OnsetOctave;
    float RidgeOnsetInitial;
    float RidgeOnsetOctave;
    float AssumedSlope;
    float AssumedSlopeBlend;
    float CellScale;
    float Normalization;
    int32_t Octaves;
    float Lacunarity;
    float Gain;
    float HeightOffset;
    float HeightOffsetFadeBlend;
};
#endif

#ifndef __ISPC_STRUCT_ProceduralOctaveConfig__
#define __ISPC_STRUCT_ProceduralOctaveConfig__
struct ProceduralOctaveConfig {
    int32_t type;
    float strength;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void VoxelPlanetErosion_Batch(const float * pos_x, const float * pos_y, const float * pos_z, const struct FCErosionParams * params, float * out_height, float * out_ridge, float * out_erosion, const int32_t count);
    extern void VoxelProceduralNoise2D_Batch(const float * pos_x, const float * pos_y, const float amplitude, const float feature_scale, const float lacunarity, const float gain, const float voronoi_smoothness, const float wavelet_phase, const float scratch_smoothness, const int32_t in_seed, const struct ProceduralOctaveConfig * octaves, const int32_t num_octaves, float * output, const int32_t count);
    extern void VoxelProceduralNoise3D_Batch(const float * pos_x, const float * pos_y, const float * pos_z, const float amplitude, const float feature_scale, const float lacunarity, const float gain, const float voronoi_smoothness, const float wavelet_phase, const float scratch_smoothness, const int32_t in_seed, const struct ProceduralOctaveConfig * octaves, const int32_t num_octaves, float * output, const int32_t count);
    extern void VoxelSphereStamp_Batch(const float * pos_x, const float * pos_y, const float * pos_z, const float center_x, const float center_y, const float center_z, const float stamp_size, const float falloff, const float rotation_degrees, const float planet_radius, float * out_local_x, float * out_local_y, float * out_uv_x, float * out_uv_y, float * out_strength, const int32_t count);
    extern void VoxelTerrainClimate2D_Batch(const float * pos_x, const float * pos_y, const float * height, const float amplitude, const float sea_level, const float climate_scale, const float elevation_cooling, const float temperature_variation, const int32_t seed, float * out_temperature, float * out_moisture, float * out_normalized_height, const int32_t count);
    extern void VoxelTerrainClimate3D_Batch(const float * pos_x, const float * pos_y, const float * pos_z, const float * radial_distance, const float amplitude, const float sea_level, const float climate_scale, const float elevation_cooling, const float temperature_variation, const int32_t seed, const float planet_radius, float * out_temperature, float * out_moisture, float * out_normalized_height, const int32_t count);
    extern void VoxelTerrainHeight2D_Batch(const float * pos_x, const float * pos_y, const float amplitude, const float feature_scale, const float lacunarity, const float gain, const float aesthetic_bias, const int32_t num_octaves, const int32_t seed, const float warp_strength, const float warp_scale, const float mountain_blend, const float mountain_scale, const float continent_blend, const float continent_scale, const float island_bias, const float canyon_blend, const float canyon_scale, const float terrace_strength, const float terrace_count, float * output, const int32_t count);
    extern void VoxelTerrainHeight3D_Batch(const float * pos_x, const float * pos_y, const float * pos_z, const float amplitude, const float feature_scale, const float lacunarity, const float gain, const float aesthetic_bias, const int32_t num_octaves, const int32_t seed, const float planet_radius, const float warp_strength, const float warp_scale, const float mountain_blend, const float mountain_scale, const float continent_blend, const float continent_scale, const float island_bias, const float canyon_blend, const float canyon_scale, const float terrace_strength, const float terrace_count, float * output, const int32_t count);
    extern void VoxelTerrainMaterialBlend_Batch(const float * normalized_height, const float * temperature, const float * moisture, const float * river_mask, const float sea_level, const float biome_contrast, float * out_biome_id, float * out_ocean_mask, float * out_coast_mask, float * out_river_feature_mask, float * out_vegetation_mask, float * out_desert_mask, float * out_tundra_mask, float * out_mountain_mask, float * out_snow_mask, const int32_t count);
    extern void VoxelTerrainRivers2D_Batch(const float * pos_x, const float * pos_y, const float * normalized_height, const float sea_level, const float river_scale, const float river_width, const float flow_strength, const int32_t seed, float * out_river_mask, float * out_river_depth, const int32_t count);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__



#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
